name: Automatic Updates

on:
  schedule:
    - cron: "29 1 * * 6"
  workflow_dispatch:

jobs:
  auto-update:
    name: Automatic Updates
    uses: juitnow/workflows/.github/workflows/auto-update.yml@main
    secrets: inherit
